is_test: true

server:
  port: 8080

database:
  host: localhost
  user: postgres
  password: secret
  port: 5432
  driver: postgres
  name: courier_db_test
  sslmode: disable

migrations:
  dir: ../../internal/database/migrations